"use client"

import { useCallback, useEffect, useState } from "react"
import { AlertCircle, ArrowLeft, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { apiGet, apiPost } from "@/lib/apiClient"

type Assessment = { id: string; entityType: string; entityId: string; riskLevel: string; score?: number; createdAt?: string; signals?: unknown[] }
export default function FraudAdminPage() {
  const [items, setItems] = useState<Assessment[]>([]); const [selected, setSelected] = useState<Assessment | null>(null); const [confirm, setConfirm] = useState(false); const [typed, setTyped] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { try { const r = await apiGet<{ assessments: Assessment[] }>("/admin/fraud/assessments?limit=100"); setItems(r.assessments); setError(null) } catch (e) { setError(e instanceof Error ? e.message : "Failed to load fraud queue") } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const release = async () => { if (!selected || typed !== "RELEASE HOLD") return; setLoading(true); try { await apiPost(`/admin/fraud/holds/${encodeURIComponent(selected.entityId)}/release`, { releasedBy: "admin" }); setConfirm(false); setTyped(""); await load() } catch (e) { setError(e instanceof Error ? e.message : "Failed to release hold") } finally { setLoading(false) } }
  return <main className="min-h-screen bg-background p-6"><div className="mx-auto max-w-5xl">{selected ? <><Button variant="ghost" onClick={() => setSelected(null)}><ArrowLeft className="mr-2 h-4 w-4" />Back to queue</Button><Card className="mt-4 border-2 border-foreground p-6"><h1 className="text-3xl font-black">Fraud case detail</h1><dl className="mt-6 grid gap-4 md:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Case ID</dt><dd className="font-mono">{selected.id}</dd></div><div><dt className="text-xs text-muted-foreground">Risk</dt><dd className="font-bold uppercase">{selected.riskLevel}</dd></div><div><dt className="text-xs text-muted-foreground">Entity</dt><dd>{selected.entityType} · {selected.entityId}</dd></div><div><dt className="text-xs text-muted-foreground">Score</dt><dd>{selected.score ?? "—"}</dd></div></dl><Button className="mt-6" variant="destructive" onClick={() => setConfirm(true)}>Release account hold</Button></Card>{confirm && <Card className="mt-6 border-2 border-destructive p-6"><h2 className="font-bold">Confirm hold release</h2><p className="mt-2">Type <strong>RELEASE HOLD</strong> to continue.</p><Input className="mt-3 border-2 border-foreground" value={typed} onChange={(e) => setTyped(e.target.value)} /><div className="mt-4 flex gap-2"><Button variant="outline" onClick={() => setConfirm(false)}>Cancel</Button><Button variant="destructive" disabled={loading || typed !== "RELEASE HOLD"} onClick={() => void release()}>{loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Confirm release</Button></div></Card>}</> : <><h1 className="mb-2 text-3xl font-black">Fraud Review Queue</h1><p className="mb-6 text-muted-foreground">Review flagged entities and take time-critical action.</p>{error && <p className="mb-4 text-destructive"><AlertCircle className="mr-2 inline h-4 w-4" />{error}</p>}<Card className="border-2 border-foreground p-6">{loading ? <p>Loading queue...</p> : items.length === 0 ? <p className="text-muted-foreground">No fraud assessments found.</p> : <div className="space-y-3">{items.map((item) => <button key={item.id} className="block w-full border-b border-foreground p-3 text-left hover:bg-muted" onClick={() => setSelected(item)}><span className="font-mono">{item.id}</span><span className="ml-4 font-bold uppercase">{item.riskLevel}</span><span className="ml-4 text-muted-foreground">{item.entityType} · {item.entityId}</span></button>)}</div>}</Card></>}</div></main>
}
