"use client"

import { useState } from "react"
import { AlertCircle, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { apiDelete, apiGet, apiPost } from "@/lib/apiClient"

type Session = { id: string; createdAt: string; expiresAt: string; lastActiveAt: string; ipHash: string | null; userAgent: string | null }
export default function AdminSessionsPage() {
  const [userId, setUserId] = useState(""); const [sessions, setSessions] = useState<Session[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [confirm, setConfirm] = useState<{ action: "all" | "one"; id?: string } | null>(null); const [typed, setTyped] = useState("")
  const load = async () => { if (!userId.trim()) return; setLoading(true); try { const r = await apiGet<{ data: Session[] }>(`/admin/sessions/${encodeURIComponent(userId.trim())}`); setSessions(r.data); setError(null) } catch (e) { setError(e instanceof Error ? e.message : "Failed to load sessions") } finally { setLoading(false) } }
  const action = async () => { if (!confirm || typed !== "REVOKE") return; setLoading(true); try { if (confirm.action === "all") await apiPost(`/admin/sessions/${encodeURIComponent(userId.trim())}/force-logout`, {}); else await apiDelete(`/admin/sessions/${confirm.id}`); setConfirm(null); setTyped(""); await load() } catch (e) { setError(e instanceof Error ? e.message : "Action failed") } finally { setLoading(false) } }
  return <main className="min-h-screen bg-background p-6"><div className="mx-auto max-w-5xl"><h1 className="mb-2 text-3xl font-black">Session Revocation</h1><p className="mb-6 text-muted-foreground">Contain compromised accounts by reviewing and revoking active sessions.</p><Card className="mb-6 border-2 border-foreground p-6"><div className="flex gap-2"><Input className="border-2 border-foreground" placeholder="User ID" value={userId} onChange={(e) => setUserId(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void load()} /><Button onClick={() => void load()} disabled={loading}>Look up</Button></div></Card>{error && <p className="mb-4 text-destructive"><AlertCircle className="mr-2 inline h-4 w-4" />{error}</p>}<Card className="border-2 border-foreground p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">Active sessions ({sessions.length})</h2><Button variant="destructive" disabled={!sessions.length || loading} onClick={() => setConfirm({ action: "all" })}>Force logout all</Button></div>{sessions.length === 0 ? <p className="text-muted-foreground">No active sessions loaded.</p> : <div className="space-y-3">{sessions.map((s) => <div key={s.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-foreground pb-3"><div><p className="font-mono text-sm">{s.id}</p><p className="text-sm text-muted-foreground">{s.userAgent || "Unknown device"} · Last active {new Date(s.lastActiveAt).toLocaleString()}</p></div><Button size="sm" variant="destructive" onClick={() => setConfirm({ action: "one", id: s.id })}>Revoke</Button></div>)}</div>}</Card>{confirm && <Card className="mt-6 border-2 border-destructive p-6"><h2 className="text-xl font-bold">Confirm session revocation</h2><p className="mt-2">Type <strong>REVOKE</strong> to continue. This action cannot be undone.</p><Input className="mt-3 border-2 border-foreground" value={typed} onChange={(e) => setTyped(e.target.value)} /><div className="mt-4 flex gap-2"><Button variant="outline" onClick={() => setConfirm(null)}>Cancel</Button><Button variant="destructive" disabled={loading || typed !== "REVOKE"} onClick={() => void action()}>{loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Confirm revocation</Button></div></Card>}</div></main>
}
